import { createContext } from 'react';

export type Language = 'en' | 'pt' | 'es';

export const translations = {
    pt: {
        dashboard: 'Dashboard',
        crm: 'CRM',
        lia: 'LIA',
        calendar: 'Calendário',
        files: 'Arquivos',
        automations: 'Automações',
        financial: 'Financeiro',
        team: 'Equipe',
        settings: 'Configurações',
        plan: 'Plano',
        support: 'Suporte',
        emails: 'E-mails',
        liaOnline: 'LIA Online',
        featureComingSoon: 'Brevemente!',
        helloUser: 'Olá!',
        searchPlaceholder: 'Busca Universal...',
        planLabel: 'Plano:',
        upgrade: 'Upgrade',
        crmTitle: 'CRM',
        pipeline: 'Pipeline',
        listView: 'Lista',
        newDeal: 'Novo Negócio',
        searchDeals: 'Buscar...',
        stageLead: 'Leads',
        stageContacted: 'Contatado',
        stageProposal: 'Proposta',
        stageNegotiation: 'Negociação',
        stageClosed: 'Fechado',
        totalValue: 'Total Pipeline',
        openDeals: 'Abertos',
        conversionRate: 'Conversão',
        client: 'Cliente',
        company: 'Empresa',
        value: 'Valor',
        stage: 'Etapa',
        email: 'Email',
        lastContact: 'Contato',
        moveStage: 'Mover',
        editDeal: 'Editar',
        deleteDeal: 'Excluir',
        saveDeal: 'Salvar',
        cancel: 'Cancelar',
        dealDetails: 'Detalhes',
        configTitle: 'Ajustes',
        settingsDesc: 'Personalize seu painel.',
        appearance: 'Aparência',
        theme: 'Tema',
        language: 'Idioma',
        accentColor: 'Cor',
        saveChanges: 'Salvar',
        darkMode: 'Dark',
        lightMode: 'Light',
        customizeAppearance: 'Aparência.',
        chooseLanguage: 'Idioma.',
        selectAccent: 'Cor.',
        saved: 'Salvo!',
        companyActivity: 'Atividade',
        newClients: 'Novos',
        conversions: 'Conversões',
        messages: 'Msgs',
        attendances: 'Atd',
        sales: 'Vendas',
        tickets: 'Tkt',
        generalPerformance: 'Performance',
        daily: 'Dia',
        weekly: 'Semana',
        monthly: 'Mês',
        yearly: 'Ano',
        threatAlert: 'Alertas',
        pending: 'Pendente',
        delays: 'Atrasos',
        problems: 'Probs',
        opportunities: 'Oportunidades',
        dailySummary: 'Resumo',
        liaOverview: '(LIA)',
        tasksToday: 'Hoje',
        liaActions: "Autônomas",
        liaSuggestion: 'LIA',
        execute: 'Executar',
        liaInsights: 'Insights',
        liaInsightsText: "78% de chance de bater metas.",
        investigate: 'Investigar',
        remindLater: 'Depois',
        quickActions: 'Ações',
        mon: 'S',
        tue: 'T',
        wed: 'Q',
        thu: 'Q',
        fri: 'S',
        sat: 'S',
        sun: 'D',
        alertApprovals: 'Aprovações.',
        alertZenith: "Atraso.",
        alertNexus: "Falha.",
        alertEngagement: "Engajamento.",
        conversationsTitle: 'Chat LIA',
        recentConversations: 'Recentes',
        newConversation: 'Novo',
        howCanIHelp: 'Ajudo hoje?',
        liaIntro: "Sou a LIA.",
        typeMessage: 'Fale com LIA...',
        analyzeData: 'Analisar',
        draftEmail: 'Email',
        summarizePDF: 'Resumir',
        myTasks: 'Minhas',
        chatHistory1: 'Q3',
        chatHistorySnippet1: 'Resumo...',
        chatHistory2: 'Campanha',
        chatHistorySnippet2: 'Slogans...',
        chatHistory3: 'Reunião',
        chatHistorySnippet3: 'Foco...',
        agendaTitle: 'Agenda',
        createEvent: 'Novo Evento',
        upcomingEvents: 'Próximos',
        liaSuggestions: 'Sugestões',
        reviewSuggestions: 'Revisar',
        eventModalTitle: 'Evento',
        editEvent: 'Editar',
        newEvent: 'Novo',
        eventTitleLabel: 'Título',
        dayLabel: 'Dia',
        timeLabel: 'Hora',
        typeLabel: 'Tipo',
        delete: 'Excluir',
        saveEvent: 'Salvar',
        today: 'Hoje',
        filesTitle: 'Arquivos',
        searchFiles: 'Buscar...',
        newFolder: 'Pasta',
        upload: 'Subir',
        root: 'Raiz',
        myFiles: 'Meus Arquivos',
        sharedFiles: 'Compartilhados',
        liaFiles: 'Arquivos da LIA',
        emptyLibrary: 'Sua biblioteca está vazia',
        emptyLibraryDesc: 'Crie pastas para se organizar ou arraste arquivos para começar o upload.',
        syncingFiles: 'Sincronizando Arquivos...',
        createNewFolder: 'Criar Nova Pasta',
        folderNameLabel: 'Nome da Pasta',
        folderPlaceholder: 'Ex: Contratos, Prints LIA...',
        folderScopeNote: 'A pasta será criada no escopo {scope} dentro do diretório atual.',
        deleteConfirm: 'Deseja realmente excluir este {type}?',
        folderDeleteSoon: 'Exclusão de pasta em breve.',
        uploadingFile: 'Subindo {name}...',
        uploadSuccess: 'Upload concluído!',
        uploadError: 'Erro no upload.',
        folderCreateSuccess: 'Pasta criada com sucesso!',
        folderCreateError: 'Erro ao criar pasta.',
        deleteSuccess: 'Excluído com sucesso!',
        automationsTitle: 'Automações',
        totalAutomations: 'Total',
        active: 'Ativo',
        paused: 'Pausado',
        error: 'Erro',
        errors24h: 'Erros',
        workflowList: 'Lista',
        searchWorkflow: 'Buscar...',
        workflowName: 'Nome',
        trigger: 'Gatilho',
        lastRun: 'Execução',
        status: 'Status',
        actions: 'Ações',
        financialTitle: 'Financeiro',
        totalBalance: 'Saldo',
        totalRevenue: 'Receita',
        totalExpenses: 'Despesas',
        revenueVsExpenses: 'Fluxo',
        expenseBreakdown: 'Detalhamento',
        recentTransactions: 'Transações',
        description: 'Descrição',
        date: 'Data',
        amount: 'Valor',
        invoice: 'Invoice',
        completed: 'OK',
        inProgress: 'In Progress',
        failed: 'Falhou',
        teamTitle: 'Equipe',
        manageRoles: 'Funções',
        inviteMember: 'Convidar',
        pendingInvitation: 'Pendente',
        awaiting: 'Aguardando',
        resend: 'Reenviar',
        addNewMember: 'Novo Membro',
        expandTeam: 'Expandir',
        admin: 'Admin',
        developer: 'Dev',
        projectManager: 'PM',
        marketing: 'Marketing',
        designer: 'Designer',
        supportRole: 'Suporte',
        planTitle: 'Plan',
        essentialPlan: 'Essencial',
        nextBilling: 'Cobrança em',
        manageSubscription: 'Gerenciar',
        cancelPlan: 'Cancelar',
        upgradePlan: 'Upgrade',
        recommended: 'TOP',
        choosePro: 'Escolher Pro',
        enterprise: 'Enterprise',
        custom: 'Custom',
        contactSales: 'Vendas',
        paymentHistory: 'Pagamentos',
        supportTitle: 'Suporte',
        howCanWeHelp: 'Ajuda?',
        searchKeywords: 'Busca...',
        quickAccess: 'Acesso',
        gettingStarted: 'Início',
        billing: 'Fatura',
        techSupport: 'TI',
        faq: 'FAQ',
        activated: 'OK',
        stock: 'Estoque',
        stockTitle: 'Estoque',
        addProduct: 'Novo',
        searchStock: 'Busca...',
        stockAdded: 'OK',
        stockUpdated: 'OK',
        projects: 'Projetos',
        logistics: 'Logística',
        logisticsTitle: 'Logística',
        logisticsDesc: 'Painel Logístico.',
        ongoingDeliveries: 'Entregas',
        delivered: 'Entregue',
        onHold: 'Espera',
        newShipment: 'Novo Envio',
        liveTracking: 'Live Map',
        warehouseStatus: 'Armazém',
        optimizeRoutes: 'Rotas',
        checkWarehouse: 'Estoque',
        generateReport: 'Relatório',
        last30Days: '30 dias',
        fromLastMonth: 'vs anterior',
        properties: 'Imóveis',
        medicalRecords: 'Prontuários',
        reports: 'Relatórios',
        whatsappAgent: 'WhatsApp (Agente)',
        intelligenceReport: 'RELATÓRIO DE INTELIGÊNCIA',
        activityReport: 'Relatório de Atividade',
        notSaved: 'Não salvo',
        loadingDashboardEngine: 'Carregando Dashboard Engine...',
        widgetNotFound: 'Widget não encontrado',
        replaceWidgetDesc: 'Escolha um novo tipo para substituir o atual.',
        noDataForPeriod: 'Sem dados para este período',
        editWidget: 'Editar Widget',
        addWidget: 'Adicionar Widget',
        searchWidgets: 'Buscar widgets...',
        allWidgets: 'Todos',
        kpiWidgets: 'KPIs',
        chartWidgets: 'Gráficos',
        tableWidgets: 'Tabelas',
        specialWidgets: 'Especiais',
        widgetTitle: 'Título',
        widgetColor: 'Cor',
        widgetMetric: 'Métrica',
        replaceWidget: 'Substituir Widget',
        removeWidget: 'Remover',
        saveWidget: 'Salvar',
        noWidgetsFound: 'Nenhum widget encontrado',
        metric_cash_in: 'Entradas (Cash In)',
        metric_cash_out: 'Saídas (Cash Out)',
        metric_net_cash: 'Saldo Líquido',
        metric_transaction_count: 'Qtd. Transações',
        metric_deals_count: 'Qtd. de Negócios',
        metric_deals_value: 'Valor de Negócios',
        metric_invoices_pending: 'Faturas Pendentes',
        metric_contacts_count: 'Total de Contatos',
        metric_revenue_by_category: 'Receita por Categoria',
        metric_expenses_by_category: 'Despesas por Categoria',
        metric_deals_by_stage: 'Negocios por Etapa',
        metric_contacts_by_type: 'Contatos por Tipo',
        metric_top_categories: 'Top Categorias',
        metric_top_customers: 'Principais Clientes',
        metric_top_products: 'Produtos Mais Vendidos',
        metric_transactions_recent: 'Transações Recentes',
        metric_deals_funnel: 'Funil de Vendas',
        metric_goal_progress: 'Progresso da Meta',
        metric_conversion_rate: 'Taxa de Conversão',
        metric_satisfaction_score: 'Score de Satisfação',
        metric_activity_by_day: 'Atividade por Dia',
        metric_transactions_by_day: 'Transações por Dia',
        metric_insights: 'Insights da LIA',
        metric_alerts: 'Alertas Críticos',
        metric_recommendations: 'Recomendações',
        widget_kpi_card_name: 'Cartão KPI',
        widget_kpi_card_desc: 'Exibe valor de métrica com delta vs período anterior',
        widget_line_timeseries_name: 'Gráfico de Linha',
        widget_line_timeseries_desc: 'Série temporal com linha ou área',
        widget_bar_grouped_name: 'Barras Agrupadas',
        widget_bar_grouped_desc: 'Gráfico de barras por categoria ou canal',
        widget_donut_breakdown_name: 'Gráfico de Rosca',
        widget_donut_breakdown_desc: 'Gráfico donut com breakdown por dimensão',
        widget_table_rank_name: 'Tabela Ranking',
        widget_table_rank_desc: 'Top N itens ordenados por métrica',
        widget_table_transactions_name: 'Transações Recentes',
        widget_table_transactions_desc: 'Lista paginada de transações',
        widget_funnel_name: 'Funil de Vendas',
        widget_funnel_desc: 'Visualização de pipeline/funil CRM',
        widget_gauge_name: 'Medidor de Meta',
        widget_gauge_desc: 'Medidor circular mostrando progresso vs meta',
        widget_heatmap_calendar_name: 'Mapa de Calor',
        widget_heatmap_calendar_desc: 'Calendário com intensidade por dia',
        widget_alerts_list_name: 'Lista de Alertas',
        widget_alerts_list_desc: 'Insights e notificações importantes',
        widget_radar_multidim_name: 'Gráfico Radar',
        widget_radar_multidim_desc: 'Análise multidimensional',
        widget_bar_horizontal_name: 'Barras Horizontais',
        widget_bar_horizontal_desc: 'Gráfico de barras horizontais para comparação',
        widget_area_timeseries_name: 'Série Temporal (Área)',
        widget_area_timeseries_desc: 'Gráfico de área para evolução de métricas',
        widget_pie_chart_name: 'Gráfico de Pizza',
        widget_pie_chart_desc: 'Gráfico de pizza clássico',
        color_green: 'Verde',
        color_blue: 'Azul',
        color_purple: 'Roxo',
        color_amber: 'Âmbar',
        color_red: 'Vermelho',
        color_cyan: 'Ciano',
        color_emerald: 'Esmeralda',
        color_pink: 'Rosa',
        total: 'Total',
        cat_servicos: 'Serviços',
        cat_produtos: 'Produtos',
        cat_assinaturas: 'Assinaturas',
        cat_consultoria: 'Consultoria',
        cat_licencas: 'Licenças',
        cat_vendas_diretas: 'Vendas Diretas',
        cat_marketing: 'Marketing',
        cat_infra: 'Infra',
        cat_suporte: 'Suporte',
        cat_operacional: 'Operacional',
        cat_pessoal: 'Pessoal',
        cat_outros: 'Outros',
        fromTotal: 'do total',
        noTransactionsFound: 'Nenhuma transação encontrada',
        importDataDesc: 'Importe dados ou conecte uma integração',
        transactionsLabel: 'transações',
        page: 'Página',
        of: 'de',
        category: 'Categoria',
        noAlerts: 'Nenhum alerta',
        everythingOk: 'Tudo em ordem por aqui!',
        ago: 'atrás',
        minutesShort: 'min',
        hoursShort: 'h',
        daysShort: 'd',
        eliteModuleActivated: 'Este módulo de elite foi ativado. Em breve, a LIA integrará funcionalidades avançadas aqui.',
        updateAvailable: 'Uma nova versão da LIA está disponível',
        later: 'Depois',
        updateNow: 'Atualizar Agora',
        initializing: 'LIA está inicializando...',
        preparingEnvironment: 'Preparando seu ambiente personalizado',
        dealUpdated: 'Negócio atualizado',
        dealCreated: 'Negócio criado',
        dealDeleted: 'Negócio removido',
        movedTo: 'Movido para',
        dealSheet: 'Ficha do Negócio',
        newPipeline: 'Novo Pipeline',
        crmManagement: 'Gestão de CRM • Zenith Intelligence',
        clientIdentification: 'Identificação do Cliente',
        relatedCompany: 'Empresa Relacionada',
        estimatedValue: 'Valor Estimado',
        salesStatus: 'Status da Venda',
        interactionTimeline: 'Cronologia de Interação',
        deleteDealBtn: 'Excluir Negócio',
        saveDealChanges: 'Salvar Alterações',
        createNewDeal: 'Criar Novo Negócio',
        businessSector: 'Ramo de Atuação',
        modulesAndApps: 'Módulos & Apps',
        themeDesc: 'Defina como o Luminnus deve aparecer para você.',
        resetPrefs: 'Zerar Preferências',
        resetPrefsDesc: 'Voltar para o estado inicial de boas-vindas.',
        resetBtn: 'Reiniciar',
        resetConfirm: 'Deseja realmente resetar o onboarding? Suas preferências atuais serão perdidas.',
        yourSector: 'Seu Ramo de Atuação',
        sectorChangeDesc: 'Mude sua profissão para que a LIA ajuste as ferramentas automaticamente.',
        activeNow: 'Ativo Agora',
        clickToChoose: 'Clique para Escolher',
        sectorChangedTo: 'Ramo alterado para:',
        loadingNewPanel: 'Carregando novo painel...',
        modulePanel: 'Painel de Módulos',
        hideShowTabsDesc: 'Ative ou oculte as abas da sua barra lateral.',
        moduleActive: 'Módulo Ativo',
        moduleHidden: 'Módulo Oculto',
        sector_technical_services: 'Serviços Técnicos',
        sector_liberal_professionals: 'Profissionais Liberais',
        sector_health_wellness: 'Saúde & Bem-Estar',
        sector_real_estate: 'Imobiliária & Construção',
        sector_retail: 'Comércio & Lojas',
        sector_logistics: 'Transporte & Logística',
        sector_tech: 'Tecnologia & Software',
        sector_creative: 'Conteúdo & Criativos',
        sector_other: 'Outros',
        vs: 'vs',
        waConfig: 'Configuração',
        waInbox: 'Inbox',
        waPipeline: 'Pipeline',
        waAudios: 'Áudios',
        waBriefings: 'Briefings',
        waSummaries: 'Resumos',
        waReconnecting: 'Solicitando reconexão...',
        waReconnected: 'Conectado com sucesso!',
        waTestingWebhook: 'Testando Webhook...',
        waWebhookProcessed: 'Webhook processado!',
        waOpeningLogs: 'Abrindo painel de logs...',
        waConnected: 'Conectado',
        sector_services_technical: 'Serviços Técnicos',
        sector_professionals: 'Profissionais Liberais',
        sector_health_wellbeing: 'Saúde & Bem-Estar',
        sector_real_estate_construction: 'Imobiliária & Construção',
        sector_commerce_retail: 'Comércio & Lojas',
        sector_food_restaurants: 'Alimentação & Restaurantes',
        sector_transport_logistics: 'Transporte & Logística',
        sector_tech_software: 'Tecnologia & Software',
        sector_content_creatives: 'Conteúdo & Criativos',
        sector_business_services: 'Serviços Empresariais',
        sector_education_training: 'Educação & Treinamento',
        sector_custom_other: 'Outros (Personalizado)',
        desc_services_technical: 'Organize atendimentos, orçamentos e serviços em campo.',
        desc_professionals: 'Gestão completa de processos, contratos e clientes.',
        desc_health_wellbeing: 'Controle agendas, pacientes e evoluções de tratamento.',
        desc_real_estate_construction: 'Gerencie imóveis, obras, propostas e clientes.',
        desc_commerce_retail: 'Administre estoque, vendas e pedidos.',
        desc_food_restaurants: 'Pedidos, cardápio, reservas e fluxo operacional.',
        desc_transport_logistics: 'Rotas, entregas, motoristas e acompanhamento.',
        desc_tech_software: 'Projetos, tickets, documentação e clientes.',
        desc_content_creatives: 'Campanhas, arquivos, postagens e clientes.',
        desc_business_services: 'Operações administrativas, financeiras e relatórios.',
        desc_education_training: 'Aulas, materiais, agenda e acompanhamento.',
        desc_custom_other: 'Descreva seu negócio e a LIA montará o painel ideal.',
        chooseBusinessType: 'Escolha o tipo do seu negócio',
        liaPreconfigure: 'A LIA irá pré-configurar os módulos ideais para sua área de atuação.',
        liaBuildingDashboard: 'A LIA está construindo seu painel modular...',
        hubIntegrations: 'Hub de Integrações',
        hubIntegrationsDesc: 'Conecte suas ferramentas favoritas para que a LIA possa automatizar tarefas.',
        openFullHub: 'Abrir Hub Completo',
        skipForNow: 'Pular por agora, configurar depois',
        tellLiaAboutBusiness: 'Conte para a LIA sobre seu negócio',
        descBusinessLiaSugg: 'Descreva o que você faz para sugerirmos os melhores módulos.',
        customDescPlaceholder: 'Ex: Sou um personal trainer focado em consultoria online...',
        categoryLabel: 'Categoria',
        productivity: 'Produtividade',
        communication: 'Comunicação',
        finance: 'Finanças',
        ecommerce: 'E-commerce',
        integrationsCount: 'integrações',
        liaTip: 'Dica da LIA:',
        liaTipDesc: 'Você pode configurar as integrações agora no Hub completo ou pular e fazer depois. Quanto mais conexões, mais inteligente eu fico!',
        preparinhHub: 'Preparando seu Hub de Integrações...',
        back: 'Voltar',
        continue: 'Continuar',
        lockedMode: 'Modo Bloqueado',
        requiresPlan: 'requer o plano',
        planToUpgrade: 'ou superior.',
        upgradeNowBtn: 'Fazer Upgrade',
        noConversations: 'Nenhuma conversa',
        connected: 'Conectado',
        disconnected: 'Desconectado',
        chatMode: 'Chat Mode',
        multimodal: 'Multi-Modal',
        liveMode: 'Live Mode',
        welcomeToChat: 'Bem-vindo ao Chat',
        welcomeChatDesc: 'Envie mensagens, arquivos ou use o microfone para interagir com a LIA.',
        typingThinking: 'LIA está pensando...',
        typingGenerating: 'LIA está gerando resposta...',
        transcribing: 'Transcrevendo...',
        typeMessagePlaceholder: 'Digite sua mensagem...',
        stopRecording: 'Parar gravação',
        startRecording: 'Gravar áudio',
        analyzeImages: 'Analise estas imagens',
        transcribeError: 'Não foi possível transcrever o áudio.',
        micAccessError: 'Não foi possível acessar o microfone.'
    },
    en: {

        dashboard: 'Dashboard',
        crm: 'CRM',
        lia: 'LIA',
        calendar: 'Calendar',
        files: 'Files',
        automations: 'Automations',
        financial: 'Financial',
        team: 'Team',
        settings: 'Settings',
        plan: 'Plan',
        support: 'Support',
        emails: 'Emails',
        liaOnline: 'LIA Online',
        featureComingSoon: 'Coming Soon!',
        helloUser: 'Hello!',
        searchPlaceholder: 'Global Search...',
        planLabel: 'Plan:',
        upgrade: 'Upgrade',
        crmTitle: 'CRM',
        pipeline: 'Pipeline',
        listView: 'List',
        newDeal: 'New Deal',
        searchDeals: 'Search...',
        stageLead: 'Leads',
        stageContacted: 'Contacted',
        stageProposal: 'Proposal',
        stageNegotiation: 'Negotiation',
        stageClosed: 'Closed',
        totalValue: 'Total Pipeline',
        openDeals: 'Open',
        conversionRate: 'Conversion',
        client: 'Client',
        company: 'Company',
        value: 'Value',
        stage: 'Stage',
        email: 'Email',
        lastContact: 'Contact',
        moveStage: 'Move',
        editDeal: 'Edit',
        deleteDeal: 'Delete',
        saveDeal: 'Save',
        cancel: 'Cancel',
        dealDetails: 'Details',
        configTitle: 'Settings',
        settingsDesc: 'Customize your panel.',
        appearance: 'Appearance',
        theme: 'Theme',
        language: 'Language',
        accentColor: 'Color',
        saveChanges: 'Save',
        darkMode: 'Dark',
        lightMode: 'Light',
        customizeAppearance: 'Appearance.',
        chooseLanguage: 'Language.',
        selectAccent: 'Color.',
        saved: 'Saved!',
        companyActivity: 'Activity',
        newClients: 'New',
        conversions: 'Conversions',
        messages: 'Msgs',
        attendances: 'Attend.',
        sales: 'Sales',
        tickets: 'Tickets',
        generalPerformance: 'Performance',
        daily: 'Day',
        weekly: 'Week',
        monthly: 'Month',
        yearly: 'Year',
        threatAlert: 'Alerts',
        pending: 'Pending',
        delays: 'Delays',
        problems: 'Issues',
        opportunities: 'Opportunities',
        dailySummary: 'Summary',
        liaOverview: '(LIA)',
        tasksToday: 'Today',
        liaActions: "Autonomous",
        liaSuggestion: 'LIA',
        execute: 'Execute',
        liaInsights: 'Insights',
        liaInsightsText: "78% chance of hitting goals.",
        investigate: 'Investigate',
        remindLater: 'Later',
        quickActions: 'Actions',
        mon: 'M',
        tue: 'T',
        wed: 'W',
        thu: 'T',
        fri: 'F',
        sat: 'S',
        sun: 'S',
        alertApprovals: 'Approvals.',
        alertZenith: "Delay.",
        alertNexus: "Failure.",
        alertEngagement: "Engagement.",
        conversationsTitle: 'LIA Chat',
        recentConversations: 'Recent',
        newConversation: 'New',
        howCanIHelp: 'How can I help?',
        liaIntro: "I am LIA.",
        typeMessage: 'Talk to LIA...',
        analyzeData: 'Analyze',
        draftEmail: 'Email',
        summarizePDF: 'Summarize',
        myTasks: 'Tasks',
        chatHistory1: 'Q3',
        chatHistorySnippet1: 'Summary...',
        chatHistory2: 'Campaign',
        chatHistorySnippet2: 'Slogans...',
        chatHistory3: 'Meeting',
        chatHistorySnippet3: 'Focus...',
        agendaTitle: 'Agenda',
        createEvent: 'New Event',
        upcomingEvents: 'Upcoming',
        liaSuggestions: 'Suggestions',
        reviewSuggestions: 'Review',
        eventModalTitle: 'Event',
        editEvent: 'Edit',
        newEvent: 'New',
        eventTitleLabel: 'Title',
        dayLabel: 'Day',
        timeLabel: 'Time',
        typeLabel: 'Type',
        delete: 'Delete',
        saveEvent: 'Save',
        today: 'Today',
        filesTitle: 'Files',
        searchFiles: 'Search...',
        newFolder: 'Folder',
        upload: 'Upload',
        root: 'Root',
        myFiles: 'My Files',
        sharedFiles: 'Shared',
        liaFiles: 'LIA Files',
        emptyLibrary: 'Your library is empty',
        emptyLibraryDesc: 'Create folders to organize or drag files to start uploading.',
        syncingFiles: 'Syncing Files...',
        createNewFolder: 'Create New Folder',
        folderNameLabel: 'Folder Name',
        folderPlaceholder: 'Ex: Contracts, LIA Prints...',
        folderScopeNote: 'The folder will be created in the {scope} scope within the current directory.',
        deleteConfirm: 'Are you sure you want to delete this {type}?',
        folderDeleteSoon: 'Folder deletion coming soon.',
        uploadingFile: 'Uploading {name}...',
        uploadSuccess: 'Upload successful!',
        uploadError: 'Upload error.',
        folderCreateSuccess: 'Folder created successfully!',
        folderCreateError: 'Error creating folder.',
        deleteSuccess: 'Successfully deleted!',
        automationsTitle: 'Automations',
        totalAutomations: 'Total',
        active: 'Active',
        paused: 'Paused',
        error: 'Error',
        errors24h: 'Errors',
        workflowList: 'List',
        searchWorkflow: 'Search...',
        workflowName: 'Name',
        trigger: 'Trigger',
        lastRun: 'Last Run',
        status: 'Status',
        actions: 'Actions',
        financialTitle: 'Financial',
        totalBalance: 'Balance',
        totalRevenue: 'Revenue',
        totalExpenses: 'Expenses',
        revenueVsExpenses: 'Flow',
        expenseBreakdown: 'Breakdown',
        recentTransactions: 'Transactions',
        description: 'Description',
        date: 'Date',
        amount: 'Amount',
        invoice: 'Invoice',
        completed: 'OK',
        inProgress: 'In Progress',
        failed: 'Failed',
        teamTitle: 'Team',
        manageRoles: 'Roles',
        inviteMember: 'Invite',
        pendingInvitation: 'Pending',
        awaiting: 'Awaiting',
        resend: 'Resend',
        addNewMember: 'New Member',
        expandTeam: 'Expand',
        admin: 'Admin',
        developer: 'Dev',
        projectManager: 'PM',
        marketing: 'Marketing',
        designer: 'Designer',
        supportRole: 'Support',
        planTitle: 'Plan',
        essentialPlan: 'Essential',
        nextBilling: 'Next Billing',
        manageSubscription: 'Manage',
        cancelPlan: 'Cancel',
        upgradePlan: 'Upgrade',
        recommended: 'TOP',
        choosePro: 'Choose Pro',
        enterprise: 'Enterprise',
        custom: 'Custom',
        contactSales: 'Sales',
        paymentHistory: 'History',
        supportTitle: 'Support',
        howCanWeHelp: 'Help?',
        searchKeywords: 'Search...',
        quickAccess: 'Access',
        gettingStarted: 'Start',
        billing: 'Billing',
        techSupport: 'Support',
        faq: 'FAQ',
        activated: 'OK',
        stock: 'Stock',
        stockTitle: 'Stock',
        addProduct: 'New',
        searchStock: 'Busca...',
        stockAdded: 'OK',
        stockUpdated: 'OK',
        projects: 'Projects',
        logistics: 'Logistics',
        logisticsTitle: 'Logistics',
        logisticsDesc: 'Logistics Panel.',
        ongoingDeliveries: 'Deliveries',
        delivered: 'Delivered',
        onHold: 'On Hold',
        newShipment: 'New Shipment',
        liveTracking: 'Live Tracking',
        warehouseStatus: 'Warehouse',
        optimizeRoutes: 'Optimize',
        checkWarehouse: 'Stock',
        generateReport: 'Report',
        last30Days: '30 Days',
        fromLastMonth: 'vs Previous',
        properties: 'Properties',
        medicalRecords: 'Medical Records',
        reports: 'Reports',
        whatsappAgent: 'WhatsApp (Agent)',
        intelligenceReport: 'INTELLIGENCE REPORT',
        activityReport: 'Activity Report',
        notSaved: 'Not saved',
        loadingDashboardEngine: 'Loading Dashboard Engine...',
        widgetNotFound: 'Widget not found',
        replaceWidgetDesc: 'Choose a new type to replace the current one.',
        noDataForPeriod: 'No data for this period',
        editWidget: 'Edit Widget',
        addWidget: 'Add Widget',
        searchWidgets: 'Search widgets...',
        allWidgets: 'All',
        kpiWidgets: 'KPIs',
        chartWidgets: 'Charts',
        tableWidgets: 'Tables',
        specialWidgets: 'Special',
        widgetTitle: 'Title',
        widgetColor: 'Color',
        widgetMetric: 'Metric',
        replaceWidget: 'Replace Widget',
        removeWidget: 'Remove',
        saveWidget: 'Save',
        noWidgetsFound: 'No widgets found',
        metric_cash_in: 'Cash In',
        metric_cash_out: 'Cash Out',
        metric_net_cash: 'Net Cash',
        metric_transaction_count: 'Transaction Count',
        metric_deals_count: 'Deals Count',
        metric_deals_value: 'Deals Value',
        metric_invoices_pending: 'Pending Invoices',
        metric_contacts_count: 'Contacts Count',
        metric_revenue_by_category: 'Revenue by Category',
        metric_expenses_by_category: 'Expenses by Category',
        metric_deals_by_stage: 'Deals by Stage',
        metric_contacts_by_type: 'Contacts by Type',
        metric_top_categories: 'Top Categories',
        metric_top_customers: 'Top Customers',
        metric_top_products: 'Top Products',
        metric_transactions_recent: 'Recent Transactions',
        metric_deals_funnel: 'Deals Funnel',
        metric_goal_progress: 'Goal Progress',
        metric_conversion_rate: 'Conversion Rate',
        metric_satisfaction_score: 'Satisfaction Score',
        metric_activity_by_day: 'Activity by Day',
        metric_transactions_by_day: 'Transactions by Day',
        metric_insights: 'LIA Insights',
        metric_alerts: 'Critical Alerts',
        metric_recommendations: 'Recommendations',
        widget_kpi_card_name: 'KPI Card',
        widget_kpi_card_desc: 'Display metric value with delta vs previous period',
        widget_line_timeseries_name: 'Line Chart',
        widget_line_timeseries_desc: 'Time series with line or area',
        widget_bar_grouped_name: 'Grouped Bars',
        widget_bar_grouped_desc: 'Bar chart by category or channel',
        widget_donut_breakdown_name: 'Donut Chart',
        widget_donut_breakdown_desc: 'Donut chart with breakdown by dimension',
        widget_table_rank_name: 'Ranking Table',
        widget_table_rank_desc: 'Top N items ordered by metric',
        widget_table_transactions_name: 'Recent Transactions',
        widget_table_transactions_desc: 'List of recent transactions',
        widget_funnel_name: 'Sales Funnel',
        widget_funnel_desc: 'CRM pipeline/funnel visualization',
        widget_gauge_name: 'Goal Gauge',
        widget_gauge_desc: 'Circular gauge showing progress vs goal',
        widget_heatmap_calendar_name: 'Heatmap',
        widget_heatmap_calendar_desc: 'Calendar with intensity per day',
        widget_alerts_list_name: 'Alerts List',
        widget_alerts_list_desc: 'Important insights and notifications',
        widget_radar_multidim_name: 'Radar Chart',
        widget_radar_multidim_desc: 'Multidimensional analysis',
        widget_bar_horizontal_name: 'Horizontal Bars',
        widget_bar_horizontal_desc: 'Horizontal bar chart for comparison',
        widget_area_timeseries_name: 'Area Chart',
        widget_area_timeseries_desc: 'Area chart for metric evolution',
        widget_pie_chart_name: 'Pie Chart',
        widget_pie_chart_desc: 'Classic pie chart',
        color_green: 'Green',
        color_blue: 'Blue',
        color_purple: 'Purple',
        color_amber: 'Amber',
        color_red: 'Red',
        color_cyan: 'Cyan',
        color_emerald: 'Emerald',
        color_pink: 'Pink',
        total: 'Total',
        cat_servicos: 'Services',
        cat_produtos: 'Products',
        cat_assinaturas: 'Subscriptions',
        cat_consultoria: 'Consulting',
        cat_licencas: 'Licenses',
        cat_vendas_diretas: 'Direct Sales',
        cat_marketing: 'Marketing',
        cat_infra: 'Infra',
        cat_suporte: 'Support',
        cat_operacional: 'Operational',
        cat_pessoal: 'Personal',
        cat_outros: 'Others',
        fromTotal: 'from total',
        noTransactionsFound: 'No transactions found',
        importDataDesc: 'Import data or connect an integration',
        transactionsLabel: 'transactions',
        page: 'Page',
        of: 'of',
        category: 'Category',
        noAlerts: 'No alerts',
        everythingOk: 'Everything is in order!',
        ago: 'ago',
        minutesShort: 'min',
        hoursShort: 'h',
        daysShort: 'd',
        eliteModuleActivated: 'This elite module has been activated. Soon, LIA will integrate advanced features here.',
        updateAvailable: 'A new version of LIA is available',
        later: 'Later',
        updateNow: 'Update Now',
        initializing: 'LIA is initializing...',
        preparingEnvironment: 'Preparing your personalized environment',
        dealUpdated: 'Deal updated',
        dealCreated: 'Deal created',
        dealDeleted: 'Deal removed',
        movedTo: 'Moved to',
        dealSheet: 'Deal Sheet',
        newPipeline: 'New Pipeline',
        crmManagement: 'CRM Management • Zenith Intelligence',
        clientIdentification: 'Client Identification',
        relatedCompany: 'Related Company',
        estimatedValue: 'Estimated Value',
        salesStatus: 'Sales Status',
        interactionTimeline: 'Interaction Timeline',
        deleteDealBtn: 'Delete Deal',
        saveDealChanges: 'Save Changes',
        createNewDeal: 'Create New Deal',
        businessSector: 'Business Sector',
        modulesAndApps: 'Modules & Apps',
        themeDesc: 'Define how Luminnus should appear to you.',
        resetPrefs: 'Reset Preferences',
        resetPrefsDesc: 'Go back to the initial welcome state.',
        resetBtn: 'Reset',
        resetConfirm: 'Do you really want to reset onboarding? Your current preferences will be lost.',
        yourSector: 'Your Business Sector',
        sectorChangeDesc: 'Change your profession so that LIA adjusts tools automatically.',
        activeNow: 'Active Now',
        clickToChoose: 'Click to Choose',
        sectorChangedTo: 'Sector changed to:',
        loadingNewPanel: 'Loading new panel...',
        modulePanel: 'Modules Panel',
        hideShowTabsDesc: 'Activate or hide the tabs on your sidebar.',
        moduleActive: 'Module Active',
        moduleHidden: 'Module Hidden',
        sector_technical_services: 'Technical Services',
        sector_liberal_professionals: 'Liberal Professionals',
        sector_health_wellness: 'Health & Wellness',
        sector_real_estate: 'Real Estate & Construction',
        sector_retail: 'Retail & Stores',
        sector_logistics: 'Transport & Logistics',
        sector_tech: 'Technology & Software',
        sector_creative: 'Content & Creative',
        sector_other: 'Other',
        vs: 'vs',
        waConfig: 'Configuration',
        waInbox: 'Inbox',
        waPipeline: 'Pipeline',
        waAudios: 'Audios',
        waBriefings: 'Briefings',
        waSummaries: 'Summaries',
        waReconnecting: 'Requesting reconnection...',
        waReconnected: 'Connected successfully!',
        waTestingWebhook: 'Testing Webhook...',
        waWebhookProcessed: 'Webhook processed!',
        waOpeningLogs: 'Opening logs panel...',
        waConnected: 'Connected',
        sector_services_technical: 'Technical Services',
        sector_professionals: 'Liberal Professionals',
        sector_health_wellbeing: 'Health & Wellness',
        sector_real_estate_construction: 'Real Estate & Constr.',
        sector_commerce_retail: 'Commerce & Retail',
        sector_food_restaurants: 'Food & Restaurants',
        sector_transport_logistics: 'Transport & Logistics',
        sector_tech_software: 'Technology & Software',
        sector_content_creatives: 'Content & Creatives',
        sector_business_services: 'Business Services',
        sector_education_training: 'Education & Training',
        sector_custom_other: 'Other (Custom)',
        desc_services_technical: 'Organize appointments, quotes and field services.',
        desc_professionals: 'Complete management of processes, contracts and clients.',
        desc_health_wellbeing: 'Control schedules, patients and treatment evolutions.',
        desc_real_estate_construction: 'Manage properties, works, proposals and clients.',
        desc_commerce_retail: 'Manage stock, sales and orders.',
        desc_food_restaurants: 'Orders, menu, reservations and operational flow.',
        desc_transport_logistics: 'Routes, deliveries, drivers and monitoring.',
        desc_tech_software: 'Projects, tickets, documentation and clients.',
        desc_content_creatives: 'Campaigns, files, posts and clients.',
        desc_business_services: 'Administrative, financial operations and reports.',
        desc_education_training: 'Classes, materials, agenda and monitoring.',
        desc_custom_other: 'Describe your business and LIA will set up the ideal panel.',
        chooseBusinessType: 'Choose your business type',
        liaPreconfigure: 'LIA will pre-configure the ideal modules for your area.',
        liaBuildingDashboard: 'LIA is building your modular dashboard...',
        hubIntegrations: 'Integrations Hub',
        hubIntegrationsDesc: 'Connect your favorite tools so LIA can automate tasks.',
        openFullHub: 'Open Full Hub',
        skipForNow: 'Skip for now, set up later',
        tellLiaAboutBusiness: 'Tell LIA about your business',
        descBusinessLiaSugg: 'Describe what you do so we can suggest the best modules.',
        customDescPlaceholder: 'Ex: I am a personal trainer focused on online consulting...',
        categoryLabel: 'Category',
        productivity: 'Productivity',
        communication: 'Communication',
        finance: 'Finance',
        ecommerce: 'E-commerce',
        integrationsCount: 'integrations',
        liaTip: 'LIA Tip:',
        liaTipDesc: 'You can configure integrations now in the full Hub or skip and do it later. The more connections, the smarter I get!',
        preparinhHub: 'Preparing your Integrations Hub...',
        back: 'Back',
        continue: 'Continue',
        lockedMode: 'Locked Mode',
        requiresPlan: 'requires plan',
        planToUpgrade: 'or higher.',
        upgradeNowBtn: 'Upgrade Now',
        noConversations: 'No conversations',
        connected: 'Connected',
        disconnected: 'Disconnected',
        chatMode: 'Chat Mode',
        multimodal: 'Multi-Modal',
        liveMode: 'Live Mode',
        welcomeToChat: 'Welcome to Chat',
        welcomeChatDesc: 'Send messages, files or use the microphone to interact with LIA.',
        typingThinking: 'LIA is thinking...',
        typingGenerating: 'LIA is generating response...',
        transcribing: 'Transcribing...',
        typeMessagePlaceholder: 'Type your message...',
        stopRecording: 'Stop recording',
        startRecording: 'Record audio',
        analyzeImages: 'Analyze these images',
        transcribeError: 'Could not transcribe audio.',
        micAccessError: 'Could not access microphone.'
    },
    es: {

        dashboard: 'Dashboard',
        crm: 'CRM',
        lia: 'LIA',
        calendar: 'Calendario',
        files: 'Archivos',
        automations: 'Automatizaciones',
        financial: 'Financiero',
        team: 'Equipo',
        settings: 'Configuración',
        plan: 'Plan',
        support: 'Soporte',
        emails: 'Correos',
        liaOnline: 'LIA Online',
        featureComingSoon: '¡Próximamente!',
        helloUser: '¡Hola!',
        searchPlaceholder: 'Búsqueda Global...',
        planLabel: 'Plan:',
        upgrade: 'Upgrade',
        crmTitle: 'CRM',
        pipeline: 'Pipeline',
        listView: 'Lista',
        newDeal: 'Nuevo Negocio',
        searchDeals: 'Buscar...',
        stageLead: 'Leads',
        stageContacted: 'Contactado',
        stageProposal: 'Propuesta',
        stageNegotiation: 'Negociación',
        stageClosed: 'Cerrado',
        totalValue: 'Total Pipeline',
        openDeals: 'Abiertos',
        conversionRate: 'Conversión',
        client: 'Cliente',
        company: 'Empresa',
        value: 'Valor',
        stage: 'Etapa',
        email: 'Email',
        lastContact: 'Contacto',
        moveStage: 'Mover',
        editDeal: 'Editar',
        deleteDeal: 'Eliminar',
        saveDeal: 'Guardar',
        cancel: 'Cancelar',
        dealDetails: 'Detalles',
        configTitle: 'Ajustes',
        settingsDesc: 'Personalice su painel.',
        appearance: 'Apariencia',
        theme: 'Tema',
        language: 'Idioma',
        accentColor: 'Color',
        saveChanges: 'Guardar',
        darkMode: 'Oscuro',
        lightMode: 'Claro',
        customizeAppearance: 'Apariencia.',
        chooseLanguage: 'Idioma.',
        selectAccent: 'Color.',
        saved: '¡Guardado!',
        companyActivity: 'Actividad',
        newClients: 'Nuevos',
        conversions: 'Conversiones',
        messages: 'Msgs',
        attendances: 'Atenc.',
        sales: 'Vendas',
        tickets: 'Tickets',
        generalPerformance: 'Desempeño',
        daily: 'Día',
        weekly: 'Semana',
        monthly: 'Mes',
        yearly: 'Año',
        threatAlert: 'Alertas',
        pending: 'Pendiente',
        delays: 'Retrasos',
        problems: 'Problemas',
        opportunities: 'Oportunidades',
        dailySummary: 'Resumen',
        liaOverview: '(LIA)',
        tasksToday: 'Hoje',
        liaActions: "Autônomas",
        liaSuggestion: 'LIA',
        execute: 'Ejecutar',
        liaInsights: 'Insights',
        liaInsightsText: "78% de probabilidad de metas.",
        investigate: 'Investigar',
        remindLater: 'Después',
        quickActions: 'Acciones',
        mon: 'L',
        tue: 'M',
        wed: 'X',
        thu: 'J',
        fri: 'V',
        sat: 'S',
        sun: 'D',
        alertApprovals: 'Aprobaciones.',
        alertZenith: "Retraso.",
        alertNexus: "Falla.",
        alertEngagement: "Compromiso.",
        conversationsTitle: 'Chat LIA',
        recentConversations: 'Recientes',
        newConversation: 'Nuevo',
        howCanIHelp: '¿Cómo ayudo?',
        liaIntro: "Soy LIA.",
        typeMessage: 'Habla con LIA...',
        analyzeData: 'Analisar',
        draftEmail: 'Email',
        summarizePDF: 'Resumir',
        myTasks: 'Tareas',
        chatHistory1: 'Q3',
        chatHistorySnippet1: 'Resumen...',
        chatHistory2: 'Campaña',
        chatHistorySnippet2: 'Slogans...',
        chatHistory3: 'Reunião',
        chatHistorySnippet3: 'Focus...',
        agendaTitle: 'Agenda',
        createEvent: 'Novo Evento',
        upcomingEvents: 'Próximos',
        liaSuggestions: 'Sugerencias',
        reviewSuggestions: 'Revisar',
        eventModalTitle: 'Evento',
        editEvent: 'Editar',
        newEvent: 'Novo',
        eventTitleLabel: 'Título',
        dayLabel: 'Día',
        timeLabel: 'Hora',
        typeLabel: 'Tipo',
        delete: 'Eliminar',
        saveEvent: 'Guardar',
        today: 'Hoy',
        filesTitle: 'Archivos',
        searchFiles: 'Buscar...',
        newFolder: 'Carpeta',
        upload: 'Subir',
        automationsTitle: 'Automatizaciones',
        totalAutomations: 'Total',
        active: 'Ativo',
        paused: 'Pausado',
        error: 'Erro',
        errors24h: 'Errores',
        workflowList: 'Lista',
        searchWorkflow: 'Buscar...',
        workflowName: 'Nombre',
        trigger: 'Disparador',
        lastRun: 'Ejecución',
        status: 'Estado',
        actions: 'Acciones',
        financialTitle: 'Financiero',
        totalBalance: 'Saldo',
        totalRevenue: 'Ingresos',
        totalExpenses: 'Gastos',
        revenueVsExpenses: 'Flujo',
        expenseBreakdown: 'Desglose',
        recentTransactions: 'Transacciones',
        description: 'Descripción',
        date: 'Fecha',
        amount: 'Valor',
        invoice: 'Factura',
        completed: 'OK',
        inProgress: 'En Progreso',
        failed: 'Falló',
        teamTitle: 'Equipo',
        manageRoles: 'Roles',
        inviteMember: 'Invitar',
        pendingInvitation: 'Pendiente',
        awaiting: 'Esperando',
        resend: 'Reenviar',
        addNewMember: 'Nuevo Miembro',
        expandTeam: 'Expandir',
        admin: 'Admin',
        developer: 'Dev',
        projectManager: 'PM',
        marketing: 'Marketing',
        designer: 'Diseñador',
        supportRole: 'Soporte',
        planTitle: 'Plan',
        essentialPlan: 'Esencial',
        nextBilling: 'Cobro en',
        manageSubscription: 'Gestionar',
        cancelPlan: 'Cancelar',
        upgradePlan: 'Upgrade',
        recommended: 'TOP',
        choosePro: 'Elegir Pro',
        enterprise: 'Enterprise',
        custom: 'Custom',
        contactSales: 'Vendas',
        paymentHistory: 'Historial',
        supportTitle: 'Soporte',
        howCanWeHelp: '¿Ayuda?',
        searchKeywords: 'Busca...',
        quickAccess: 'Accesso',
        gettingStarted: 'Inicio',
        billing: 'Factura',
        techSupport: 'Soporte',
        faq: 'FAQ',
        activated: 'OK',
        stock: 'Stock',
        stockTitle: 'Inventario',
        addProduct: 'Nuevo',
        searchStock: 'Busca...',
        stockAdded: 'OK',
        stockUpdated: 'OK',
        projects: 'Projetos',
        logistics: 'Logística',
        logisticsTitle: 'Logística',
        logisticsDesc: 'Painel Logístico.',
        ongoingDeliveries: 'Entregas',
        delivered: 'Entregado',
        onHold: 'Espera',
        newShipment: 'Nuevo Envío',
        liveTracking: 'Rastreo',
        warehouseStatus: 'Almacén',
        optimizeRoutes: 'Rutas',
        checkWarehouse: 'Stock',
        generateReport: 'Informe',
        last30Days: '30 dias',
        fromLastMonth: 'vs anterior',
        properties: 'Inmuebles',
        medicalRecords: 'Historias Clínicas',
        reports: 'Informes',
        whatsappAgent: 'WhatsApp (Agente)',
        intelligenceReport: 'INFORME DE INTELIGENCIA',
        activityReport: 'Informe de Actividad',
        notSaved: 'No guardado',
        loadingDashboardEngine: 'Cargando Dashboard Engine...',
        widgetNotFound: 'Widget no encontrado',
        replaceWidgetDesc: 'Elija un nuevo tipo para reemplazar el actual.',
        noDataForPeriod: 'Sin datos para este periodo',
        editWidget: 'Editar Widget',
        addWidget: 'Añadir Widget',
        searchWidgets: 'Buscar widgets...',
        allWidgets: 'Todos',
        kpiWidgets: 'KPIs',
        chartWidgets: 'Gráficos',
        tableWidgets: 'Tablas',
        specialWidgets: 'Especiais',
        widgetTitle: 'Título',
        widgetColor: 'Color',
        widgetMetric: 'Métrica',
        replaceWidget: 'Reemplazar Widget',
        removeWidget: 'Eliminar',
        saveWidget: 'Guardar',
        noWidgetsFound: 'No se encontraron widgets',
        metric_cash_in: 'Entradas',
        metric_cash_out: 'Salidas',
        metric_net_cash: 'Saldo Neto',
        metric_transaction_count: 'Cant. Transacciones',
        metric_deals_count: 'Cant. Negocios',
        metric_deals_value: 'Valor Negocios',
        metric_invoices_pending: 'Facturas Pendentes',
        metric_contacts_count: 'Total Contactos',
        metric_revenue_by_category: 'Ingresos por Categoría',
        metric_expenses_by_category: 'Gastos por Categoría',
        metric_deals_by_stage: 'Negocios por Etapa',
        metric_contacts_by_type: 'Contactos por Tipo',
        metric_top_categories: 'Top Categorías',
        metric_top_customers: 'Clientes Principales',
        metric_top_products: 'Productos Más Vendidos',
        metric_transactions_recent: 'Transacciones Recientes',
        metric_deals_funnel: 'Embudos de Ventas',
        metric_goal_progress: 'Progresso Meta',
        metric_conversion_rate: 'Tasa Conversión',
        metric_satisfaction_score: 'Puntuación Satisfacción',
        metric_activity_by_day: 'Actividad por Día',
        metric_transactions_by_day: 'Transacciones por Día',
        metric_insights: 'LIA Insights',
        metric_alerts: 'Alertas Críticas',
        metric_recommendations: 'Recomendaciones',
        widget_kpi_card_name: 'Tarjeta KPI',
        widget_kpi_card_desc: 'Muestra el valor de la métrica con delta vs período anterior',
        widget_line_timeseries_name: 'Gráfico de Línea',
        widget_line_timeseries_desc: 'Serie temporal con línea o área',
        widget_bar_grouped_name: 'Barras Agrupadas',
        widget_bar_grouped_desc: 'Gráfico de barras por categoria o canal',
        widget_donut_breakdown_name: 'Gráfico de Rosca',
        widget_donut_breakdown_desc: 'Gráfico donut con desglose por dimensión',
        widget_table_rank_name: 'Tabla Ranking',
        widget_table_rank_desc: 'Top N ítems ordenados por métrica',
        widget_table_transactions_name: 'Transacciones Recientes',
        widget_table_transactions_desc: 'Lista paginada de transacciones',
        widget_funnel_name: 'Embudo de Ventas',
        widget_funnel_desc: 'Visualización de pipeline/embudo CRM',
        widget_gauge_name: 'Medidor de Meta',
        widget_gauge_desc: 'Medidor circular que muestra progreso vs meta',
        widget_heatmap_calendar_name: 'Mapa de Calor',
        widget_heatmap_calendar_desc: 'Calendario con intensidad por día',
        widget_alerts_list_name: 'Lista de Alertas',
        widget_alerts_list_desc: 'Insights y notificaciones importantes',
        widget_radar_multidim_name: 'Gráfico Radar',
        widget_radar_multidim_desc: 'Análisis multidimensional',
        widget_bar_horizontal_name: 'Barras Horizontales',
        widget_bar_horizontal_desc: 'Gráfico de barras horizontales para comparación',
        widget_area_timeseries_name: 'Serie Temporal (Área)',
        widget_area_timeseries_desc: 'Gráfico de área para evolución de métricas',
        widget_pie_chart_name: 'Gráfico de Tarta',
        widget_pie_chart_desc: 'Gráfico de tarta clásico',
        color_green: 'Verde',
        color_blue: 'Azul',
        color_purple: 'Morado',
        color_amber: 'Ámbar',
        color_red: 'Rojo',
        color_cyan: 'Cian',
        color_emerald: 'Esmeralda',
        color_pink: 'Rosa',
        total: 'Total',
        cat_servicos: 'Servicios',
        cat_produtos: 'Productos',
        cat_assinaturas: 'Suscripciones',
        cat_consultoria: 'Consultoría',
        cat_licencas: 'Licencias',
        cat_vendas_diretas: 'Ventas Directas',
        cat_marketing: 'Marketing',
        cat_infra: 'Infra',
        cat_suporte: 'Soporte',
        cat_operacional: 'Operacional',
        cat_pessoal: 'Personal',
        cat_outros: 'Otros',
        fromTotal: 'del total',
        noTransactionsFound: 'No se encontraron transacciones',
        importDataDesc: 'Importe datos o conecte una integración',
        transactionsLabel: 'transacciones',
        page: 'Página',
        of: 'de',
        category: 'Categoría',
        noAlerts: 'No alertas',
        everythingOk: '¡Todo está en orden!',
        ago: 'atrás',
        minutesShort: 'min',
        hoursShort: 'h',
        daysShort: 'd',
        eliteModuleActivated: 'Este módulo de élite ha sido activado. Pronto, LIA integrará funciones avanzadas aquí.',
        updateAvailable: 'Una nueva versión de LIA está disponible',
        later: 'Después',
        updateNow: 'Actualizar Ahora',
        initializing: 'LIA se está inicializando...',
        preparingEnvironment: 'Preparando su entorno personalizado',
        dealUpdated: 'Negocio actualizado',
        dealCreated: 'Negocio creado',
        dealDeleted: 'Negocio eliminado',
        movedTo: 'Movido a',
        dealSheet: 'Ficha de Negocio',
        newPipeline: 'Nuevo Pipeline',
        crmManagement: 'Gestión de CRM • Zenith Intelligence',
        clientIdentification: 'Identificación del Cliente',
        relatedCompany: 'Empresa Relacionada',
        estimatedValue: 'Valor Estimado',
        salesStatus: 'Estado de Venta',
        interactionTimeline: 'Cronología de Interacción',
        deleteDealBtn: 'Eliminar Negocio',
        saveDealChanges: 'Guardar Cambios',
        createNewDeal: 'Crear Nuevo Negocio',
        businessSector: 'Sector de Actividad',
        modulesAndApps: 'Módulos y Apps',
        themeDesc: 'Define cómo debe aparecer Luminnus para ti.',
        resetPrefs: 'Restablecer Preferencias',
        resetPrefsDesc: 'Voltar al estado inicial de bienvenida.',
        resetBtn: 'Reiniciar',
        resetConfirm: '¿Realmente desea restablecer el onboarding? Se perderán sus preferencias actuales.',
        yourSector: 'Su Sector de Actividad',
        sectorChangeDesc: 'Cambie su profesión para que LIA ajuste las herramientas automáticamente.',
        activeNow: 'Activo Ahora',
        clickToChoose: 'Haga clic para Elegir',
        sectorChangedTo: 'Sector cambiado a:',
        loadingNewPanel: 'Cargando nuevo panel...',
        modulePanel: 'Panel de Módulos',
        hideShowTabsDesc: 'Active u oculte las pestañas de su barra lateral.',
        moduleActive: 'Módulo Activo',
        moduleHidden: 'Módulo Oculto',
        sector_technical_services: 'Servicios Técnicos',
        sector_liberal_professionals: 'Profesionales Liberales',
        sector_health_wellness: 'Salud y Bienestar',
        sector_real_estate: 'Inmobiliaria y Construcción',
        sector_retail: 'Comercio y Tiendas',
        sector_logistics: 'Transporte y Logística',
        sector_tech: 'Tecnología y Software',
        sector_creative: 'Contenido y Creativos',
        sector_other: 'Otros',
        vs: 'vs',
        waConfig: 'Configuración',
        waInbox: 'Inbox',
        waPipeline: 'Pipeline',
        waAudios: 'Audios',
        waBriefings: 'Briefings',
        waSummaries: 'Resúmenes',
        waReconnecting: 'Solicitando reconexión...',
        waReconnected: 'Conectado con éxito!',
        waTestingWebhook: 'Probando Webhook...',
        waWebhookProcessed: '¡Webhook procesado!',
        waOpeningLogs: 'Abriendo panel de logs...',
        waConnected: 'Conectado',
        sector_services_technical: 'Servicios Técnicos',
        sector_professionals: 'Profesionales Liberales',
        sector_health_wellbeing: 'Salud y Bienestar',
        sector_real_estate_construction: 'Inmobiliaria y Construcción',
        sector_commerce_retail: 'Comercio y Tiendas',
        sector_food_restaurants: 'Alimentación y Restaurantes',
        sector_transport_logistics: 'Transporte y Logística',
        sector_tech_software: 'Tecnología y Software',
        sector_content_creatives: 'Contenido y Creativos',
        sector_business_services: 'Servicios Empresariales',
        sector_education_training: 'Educación y Entrenamiento',
        sector_custom_other: 'Otros (Personalizado)',
        desc_services_technical: 'Organice citas, presupuestos y servicios de campo.',
        desc_professionals: 'Gestión completa de procesos, contratos y clientes.',
        desc_health_wellbeing: 'Controlar horarios, pacientes y evoluciones de tratamiento.',
        desc_real_estate_construction: 'Gestionar propiedades, obras, propuestas y clientes.',
        desc_commerce_retail: 'Gestionar stock, ventas y pedidos.',
        desc_food_restaurants: 'Pedidos, menú, reservas y flujo operativo.',
        desc_transport_logistics: 'Rutas, entregas, conductores y seguimiento.',
        desc_tech_software: 'Proyectos, tickets, documentación y clientes.',
        desc_content_creatives: 'Campañas, archivos, publicaciones y clientes.',
        desc_business_services: 'Operaciones administrativas, financieras e informes.',
        desc_education_training: 'Clases, materiales, agenda y seguimiento.',
        desc_custom_other: 'Describa su negocio y LIA configurará el panel ideal.',
        chooseBusinessType: 'Elija su tipo de negocio',
        liaPreconfigure: 'LIA preconfigurará los módulos ideales para su área.',
        liaBuildingDashboard: 'LIA está construyendo su panel modular...',
        hubIntegrations: 'Hub de Integraciones',
        hubIntegrationsDesc: 'Conecte sus herramientas favoritas para que LIA pueda automatizar tareas.',
        openFullHub: 'Abrir Hub Completo',
        skipForNow: 'Omitir por ahora, configurar después',
        tellLiaAboutBusiness: 'Cuéntele a LIA sobre su negocio',
        descBusinessLiaSugg: 'Describa lo que hace para que podamos sugerir los mejores módulos.',
        customDescPlaceholder: 'Ej: Soy un entrenador personal enfocado en consultoría online...',
        categoryLabel: 'Categoría',
        productivity: 'Productividad',
        communication: 'Comunicación',
        finance: 'Finanzas',
        ecommerce: 'E-commerce',
        integrationsCount: 'integraciones',
        liaTip: 'Consejo de LIA:',
        liaTipDesc: 'Puede configurar las integraciones ahora en el Hub completo o saltar y hacerlo más tarde. ¡Cuantas más conexiones, más inteligente me vuelvo!',
        preparinhHub: 'Preparando su Hub de Integraciones...',
        back: 'Volver',
        continue: 'Continuar',
        lockedMode: 'Modo Bloqueado',
        requiresPlan: 'requiere el plan',
        planToUpgrade: 'o superior.',
        upgradeNowBtn: 'Mejorar Plan',
        noConversations: 'Sin conversaciones',
        connected: 'Conectado',
        disconnected: 'Desconectado',
        chatMode: 'Modo Chat',
        multimodal: 'Multi-Modal',
        liveMode: 'Modo Live',
        welcomeToChat: 'Bienvenido al Chat',
        welcomeChatDesc: 'Envíe mensajes, archivos o use el micrófono para interactuar con LIA.',
        typingThinking: 'LIA está pensando...',
        typingGenerating: 'LIA está generando respuesta...',
        transcribing: 'Transcribiendo...',
        typeMessagePlaceholder: 'Escriba su mensaje...',
        stopRecording: 'Detener grabación',
        startRecording: 'Grabar audio',
        micDisabledLive: 'El micrófono está desactivado mientras Gemini Live está activo.',
        analyzeImages: 'Analice estas imágenes',
        transcribeError: 'No se pudo transcribir el audio. Inténtelo de nuevo.',
        micAccessError: 'No se pudo acceder al micrófono. Verifique los permisos del navegador.'
    }
};

export const LanguageContext = createContext<{
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}>({
    language: 'pt',
    setLanguage: () => { },
    t: (key: string) => key,
});
